#! /bin/sh
#
#

RUNDIR=jena
TOP=/Users/chenyingshan/Desktop/PaulGibbonCode/propag
 
mkdir -p $RUNDIR
cd $RUNDIR

# Copy input parameters to namelist file

rm fort.10
cat <<'EOF'>fort.10

Jena He gas jet experiment 2004

- Laser: power <=12 TW, I0=10^19
	 pulse length = 80 fs
	 spot size = 5 microns
     	 wavelength = 0.8 microns

- Gas jet:  Helium
	    gas density <= 5x10^19 cm^-3 

- Focussing optics: f/5 ??

 $idynf
   trun = 2000.
   den0 = 2.e19
   gas = 'He'
   zplas = 1000.
   zbord = 100.
   zfoff = 0.
   rl = 200.
   zl = 200.
   nr = 200
   nz = 200
   igrid = 1
   dt = 0.4

   ilas = 4
   ptw = 2.
   xi0 = 0.
   xlam = 0.8
   tau=80.
   sigma = 10.
   t0=100.
   tprobe = 0.
   fno = 5.
   Dlens = 100.
   fpol = 0.5

   rplmax = 50.
   igr= 500
   iout =100
   ihist =10
   imovie =200
   izsurf = 25

   inorm = 2
   melec = 1
   mrel = 1
   mfoc = 1
   mioniz = 1
   mplas = 3

   nitem = 3
   mabs = 1
   nabs = 15
   ncon = 4
   pcon(1) = 0.5,0.64,0.7,0.86
   ipcon = 3
   xnumin = 1.e-2
   xnumax = 0.1
   isurf = 1
   ksurf = 2
   isubm = 2
 $end   



Glossary
========

  wp0       ratio wp/w0
  tau       laser pulse length (in w0**-1)
  xlam      laser wavelength (microns)
 power      laser power in TW
  xi0       focussed laser intensity (Wcm**-2)
  a0        laser quiver amplitude (vosc/c)

  inorm     1 = time in w0**-1
            2 = time, zl, tau, t0, dt in fs; trun, sigma, rl,  in microns
            3 = time in wp**-1
   
  melec     0 = uniform, static (no Fpond)
            1 = adiabatic
            2 = dynamic

   mrel     1 = rel. self-foc on (0=off)

   mfoc     0 = pulse with flat phase fronts
            1 = pulse with curved phase fronts (lens)

  mplas     0 = infinite  zedge <0, zend > zl
            1 = semi-infinite: zedge<0, zend(0) = zplas
            2 = finite, length zplas, focus at centre
	    3 = gas jet, focus at leading edge

 mioniz     0 = sharp-edged pre-plasma
            1 = include ionization
            2 = preplasma with tanh borders

  Pulse
  -----
    ilas:   1  .....   a(x,t) = a0 exp(-x**2/sigma**2) sech( 2(t-tdel)/tp )
            2  .....   a(x,t) = gaussian*sqrt(t/tp), t<tp; const t>=tp
            3  .....   a(x,t) = gaussian*gaussian
            4  .....   NLSE propag with initial gaussian a0exp(-x**2/2/sig**2)
                            - sigma 1/e intensity

 Lens
 ----
     fno    f-number
     Dlens  lens diameter as fraction of radial grid length


  Absorber on RH boundary
  -----------------------
     nabs   # absorber points
   xnumin   min value at r = R - nabs*dr
   xnumax   max value at r = R


  Grid
  ----
     igrid: 1 ...  uniform
            2 ...  Gaussian (constant action weighting)

  Power contours
  --------------
     ncon  ...  # contours to plot in power.ps
     pcon  ...  contour levels i/p as fraction of initial laser power
    ipcon  ...  selected level to plot with other time-history plots

EOF
echo
echo "Running drelp ..."
echo "Results in directory $RUNDIR/"
echo
rm -r *.xy *.sdat *.snap *.dat header oddata
$TOP/src/drelp
mv fort.15 run.out
mv fort.50 oddata
mv fort.70 i0.2d
mv fort.71 rho.2d
mv fort.72 thom.2d
echo
cd ..


